### PR TITLE
Document POST end point configuration and remove http references to Charm

### PR DESCRIPTION
**Pull request by thbar**
Work on #1; custom post end point was already supported, I just documented it and changed the configuration name.

Additional useful resources which I did not include yet but that were required to get things working here:
- add support for Rails authenticity_token (368cbcd4c542158276662608da6ff1402e77d48c)
- harcode assets path for Rails 3 (7559bf68158c21894f305c2af7ea94ca3ce997be - until we have a configurable option for this)

I'm unsure about the removal of `tab.href` - I understand it was to redirect to a Charm-hosted page that just shows the popup, but I have no idea if no href can cause issues on a given browser.

Let me know if anything needs some polishing!

### CODE REVIEW

**Comment by madrobby** [comment]
Yes, a href would be good. It's for when you right-click and say "open in new tab". The empty page with just the popup is also useful in other situations (you can use that as a link from say where you need to leave a support URL, like the Mac or iOS App Store).

**Comment by thbar** [comment]
Thanks - I'll document how to just show a popup on a blank page so that the href can work (something I just understood).

Ok on "url" - can we assume that href and post url will be the same for now (and equal to this "url")?

**Comment by madrobby** [comment]
Sure that sounds good. We can add more config later, let's keep it simple.

**Comment by thbar** [comment]
If you'd like to incorporate some ruby sample for the server side under an `example` folder maybe, let me know, I can share that too.

**Comment by madrobby** [comment]
Examples sound good!

**Pull request merged**
